apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: express-app-cicd-demo
  name: express-app-cicd-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-app-cicd-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: express-app-cicd-demo
    spec:
      containers:
        - image: saikrishnareddy01/express-app-cicd:20
          name: express-app-cicd-demo
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: express-app-cicd-demo
